version: '3'

services:
  bugzilla-mysql:
    image: mysql:5.7
    container_name: bugzilla-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: bugs
      MYSQL_USER: bugs
      MYSQL_PASSWORD: bugs
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-ppassword"]
      interval: 10s
      timeout: 5s
      retries: 5

  bugzilla:
    build:
      context: .
      dockerfile: Dockerfile
    image: pathfinder-bugzilla:latest
    container_name: bugzilla
    depends_on:
      bugzilla-mysql:
        condition: service_healthy
    ports:
      - "8080:80"
    environment:
      # База данных
      DB_NAME: bugs
      DB_USER: bugs
      DB_PASS: bugs
      DB_HOST: bugzilla-mysql
      DB_PORT: 3306
      
      # Администратор
      BUGZILLA_ADMIN_EMAIL: admin@example.com
      BUGZILLA_ADMIN_PASSWORD: admin123
      BUGZILLA_ADMIN_REALNAME: "Администратор"
      
      # URL
      BUGZILLA_URL: http://localhost:8080
    volumes:
      - bugzilla_data:/var/www/html/bugzilla/data
      - ./scripts:/scripts
    command: >
      bash -c "
        # Ожидание полной инициализации всех сервисов
        sleep 30 &&
        
        # Запуск скрипта создания демо-данных
        chmod +x /scripts/init-bugzilla.sh &&
        /scripts/init-bugzilla.sh
      "

volumes:
  mysql_data:
  bugzilla_data: